### ISSUE TITLE
[Array + JSON handling] Query nested data from objects from Mongo

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#128]
This increment describes the ability to:
- Discover data on a node via a nested identity. In other words, one collection has its identity data in a nested object

```
dataset:
  - fides_key: example
    name: Users
    collections:
      - name: user
        fields:
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: username
            data_categories: [user.provided.identifiable]
          - name: email
            data_categories: [user.provided.identifiable]
            fidesops_meta:
              identity: email
          - name: comments
            fidesos_meta:
              data_type: object[]
            - fields:
              - name: id
                data_categories: [system.operations]
              - name: content
                data_categories: [user.provided]
              - name: email
                data_categories: [user.provided]
                fidesops_meta:
                  identity: email
```
— here if `joe@example.com` submits a privacy request, and that email is only found in objects within `user.comments`, then that data can be retrieved as an identity.

- Reference one node from another via a nested object field

```
dataset:
  - fides_key: example
    name: Users
    collections:
      - name: mailing_list
        fields:
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: emails
            data_categories: [user.derived]
            fidesos_meta:
              data_type: object[]
              fields:
                - name: email
                  references:
                    - dataset: example
                      field: user.email
                      direction: to

      - name: user
        fields:
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: email
            data_categories: [user.provided]
            fidesos_meta:
              data_type: string
```
— here `mailing_list.emails[].email` points to `user.email`

- Retrieve data with a data_category that applies to a nested object field, for example we want to get phone numbers, and mongo_example::customer_details::preferences.backups.phone field has a data category of [user.provided.identifiable.contact.phone_number]

```
dataset:
  - fides_key: example
    name: Users
    collections:
      - name: user
        fields:
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: username
            data_categories: [user.provided.identifiable]
          - name: email
            data_categories: [user.provided.identifiable]
            fidesops_meta:
              identity: email
          - name: comments
            fidesos_meta:
              data_type: object[]
            - fields:
              - name: id
                data_categories: [system.operations]
              - name: content
                data_categories: [user.provided]
              - name: email
                data_categories: [user.provided]
                fidesops_meta:
                  identity: email
```
— here any query for `user` data will retrieve `comment.content` and `comment.email`

Other requirements:
- [ ] Add logic to the Dataset validation to ensure fields with `data_type: object` cannot have `data_categories: [...]`

NB. Erasure via nested object fields will happen as part of a subsequent increment
NB. This increment is Mongo specific for now, and can be extended to other data stores at a future point

**Comment by seanpreston** [comment]
@pattisdr and I were discussing yesterday an ideal way to handle data categories within (potentially infinitely) nested objects. Initially there was concern around what to do when the data categories of a field within an object conflict with the data category of the object itself.

Some options we considered were:
- fields within objects automatically inherit the object's data categories,
- fields within objects must be manually tagged with data categories and anything without a tag is ignored

Ultimately we understood that for a seamless developer experience objects and nested objects should function no different to table joins within the mapping. For example:

```
{
    "user": {
        "id": 1,
        "username": "joe",
        "comments": [
            {
                "id": 2,
                "content": "hello i am joe"
            }
        ],
        "tags": [{
            "id": 3,
            "name": "person",
            "created_at": 12345
        }, {
            "id": 4,
            "name": "likes-to-comment",
            "created_at": 678910
        }]
    }
}
```

can be represented by

```
dataset:
  - fides_key: example
    name: Users
    collections:
      - name: user
        fields:
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: username
            data_categories: [user.provided.identifiable]

      - name: tags
        fields:
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: user_id
            data_categories: [system.operations]
            fidesops_meta:
              references:
                - dataset: example
                  field: user.id
                  direction: to
          - name: name
            data_categories: [user.derived]
          - name: created_at
            data_categories: [user.derived]
```

or

```
dataset:
  - fides_key: example
    name: Users
    collections:
      - name: user
        fields:
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: username
            data_categories: [user.provided.identifiable]
          - name: tags
            # data_categories: [user.derived]
            fidesos_meta:
              data_type: object[]
            - fields:
              - name: id
                data_categories: [system.operations]
              - name: name
                data_categories: [user.derived]
              - name: created_at
                data_categories: [user.derived]
```

When you frame things like this the clear choice is to disallow specifying data categories on any object itself, and only allow data categories at field level.

**Comment by NevilleS** [comment]
Yes, that makes sense and is consistent with our general principle for `fidesctl` evaluations: fields do not "inherit" the declarations of their parent, they are just composed. So for example, if you have this object:
```
dataset:
- fides_key: eval_example
  collections:
  - name: collection_example
    data_categories: [system]
    fields:
    - name: field_one
       data_categories: [user.provided]
       fields:
       - name: field_two
          data_categories: [user.derived]
````
In this case, the evaluation logic has two potential options:
1. Treat the `eval_example` dataset as just being `system` data, since that's the top-level category
2. Treat the `eval_example` dataset as being composed of `system`, `user.provided`, and `user.derived` data, as there are nested elements with those declarations

We do the latter- individual fields must specify their data categories individually, they don't inherit anything from parents. So this looks good to me.

**HOWEVER**: there's nothing preventing us from stating that a nested `object` field might have a data category declaration, right? The language syntax supports it, so you'd need to be adding a net-new validation error in `fidesops` or something to prevent that

**Comment by seanpreston** [comment]
> HOWEVER: there's nothing preventing us from stating that a nested object field might have a data category declaration, right?

You're right, good spot — we should add an extra validation error here that's raised when object types within datasets are given data categories.

**Comment by pattisdr** [comment]
@seanpreston, product question, are there preferences for how nested data might be returned to the user?  
A) In its original form or B) With nested fields flattened?  I might expect A personally, but not strongly.

See example below:

Say a `postgres` database has a  `users` collection with one object field `contact_information`.  Say we want the `alt_email` field.

```yaml
dataset:
  - fides_key: postgres_example
    name: Postgres DB
    collections:
      - name: users
        fields:
          - name: contact_information
             fields:
               - name: ssn
               - name: phone
               - name: alt_email
```

A) Would JSON data returned to the user be shaped in its original structure?

```json
{
   "postgres_example: users": [
    {
      "contact_information": {
            "alt_email": "customer-alt-1@example.com"
      } 
    }]
}
```

B) or would it be flattened?

```json
{
   "postgres_example: users": [
      {"contact_information.alt_email":"customer-alt-1@example.com"}
  ]
}
```
