### ISSUE TITLE
[Array + JSON Handling] Query nested data from arrays from Mongo

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#146]
When given a Dataset specification containing an array:

```
          - name: tags
            fidesops_meta:
                data_type: string[]
            data_categories: [user.provided]
```

we have a few separate use cases:
- `tags` can contain a root identity
- `tags` cannot contain a root identity

Fidesops must:
- Treat each element within the array as each data category within `data_categories` for access and retrieval purposes — e.g.
```
["dawn@ethyca.com", "sean@ethyca.com", "steven@ethyca.com"]
```
must mask all values if the field is not an identity, resulting in:
```
["masked", "masked", "masked"]
```

- Be able to mask and retrieve an identity from within an array — e.g.
```
["dawn@ethyca.com", "sean@ethyca.com", "steven@ethyca.com"]
```
must be able to mask only `steven@ethyca.com` if the field is an identity, resulting in:
```
["dawn@ethyca.com", "sean@ethyca.com", "masked"]
```

NB. Here I'm using the word `masked` to denote the result of the policy's masking strategy applied to the value.

Questions:
- Is it feasible to support nested arrays at this stage? — e.g.
```
[
  ["dawn@ethyca.com", "sean@ethyca.com"],
  ["steven@ethyca.com"]
]
```
must result in:
```
[
  ["dawn@ethyca.com", "sean@ethyca.com"],
  ["masked"]
]
```
if the field is an identity and `steven@ethyca.com` is passed as the value, and
```
[
  ["masked", "masked"],
  ["masked"]
]
```
if not.

I understand that support will also need to be added at the Dataset level here too (https://github.com/ethyca/fidesops/blob/0157344397ae4ebca56a8b8169e362b2b17ae198/tests/util/test_dataset_yaml.py#L36)

**Comment by pattisdr** [comment]
My main question here is are we supporting fetching/masking a specific index of an array, or are we only going to fetch/mask the entire array?

**Comment by seanpreston** [comment]
Since all elements of an array will be classed as the same data category, it stands to reason we wouldn't support masking and retrieving specific indexes, since policy rules apply to data categories.

**Comment by pattisdr** [comment]
thanks for taking the time to spell out some requirements @seanpreston! 

Will we support masking an identity in an array of dicts?
[{"email": "dawn@ethyca.com"}, {"email": "sean@ethyca.com"}, {"email": {"steven@ethyca.com"}]


Will we support masking an identity in an array inside of nested objects?
```
{
   "people":{
      "employees":[
         "dawn@example.com",
         "sean@example.com"
      ],
      "customers":[
         "customer-1@example.com",
         "customer-2@example.com"
      ]
   }
}
```

Are we going to impose limits on levels of nesting?

**Comment by seanpreston** [comment]
I'm going to answer these questions in reverse order and hopefully it makes sense why at the end

> Will we support masking an identity in an array inside of nested objects?

I've agreed with @iamkelllly to table this requirement for now in favour of getting the others done first. The main issues here are:
- we have no agreed language for denoting nested arrays `[string[]]` vs. `string[][]` vs. `array[string[]]` etc...
- in large datasets it can get computationally very expensive to search infinitely nested arrays for all occurrences of one value
- as you suggest, if we have a sane depth limit this problem can be limited. I'd propose designing this with a depth limit of 1 to start with and we can tweak (or allow others to tweak in the config settings as they wish)


> Will we support masking an identity in an array of dicts?

Yes, this is akin to the `comments` example where:

```
          - name: comments
            fidesops_meta:
                data_type: object[]
            fields:
              - name: comment_id
              - name: text
              - name: email
                 data_categories: [user.provided.identifiable.contact.email]
                 fidesops_meta:
                   identity: email
```

is valid, since we can give the nested `email` key the same attributes as another other field. This will always be defined, so we know the depth at which we're searching for identities, and thus don't have quite so bad a search problem as in arrays above. We might also want to apply the nesting limit here too for consistency.

**Comment by pattisdr** [comment]
OK thanks @seanpreston, in other words, as a first pass, we will support array querying for which we already have the developed language.

**Comment by pattisdr** [comment]
It seems like we can describe my example for "Will we support masking an identity in an array inside of nested objects?" with the yaml then:

```json
{
   "people":{
      "employees":[
         "dawn@example.com",
         "sean@example.com"
      ],
      "customers":[
         "customer-1@example.com",
         "customer-2@example.com"
      ]
   }
}
```

```yaml
dataset:
  - fides_key: array_inside_nested_object_example
    name: Array inside nested object emaple
    description: Example of a Mongo dataset that contains nested data
    collections:
      - name: main
        fields:
          - name: people
            fields:
              - name: employees
                fidesops_meta:
                    data_type: string[]
              - name: customers
                data_categories: [user.provided.identifiable]
                fidesops_meta:
                    data_type: string[]
```

**Comment by pattisdr** [comment]
Another question I have is how tables should reference each other in the yaml if the linking field is in an object:

Here I have a dataset with two collections.  

The "people" collection has one object field "clients". The clients object has two fields, an array of all emails that are relevant to the client, and an id string field.

The "login" collection has three fields: customer id (int), id(int) and a time.  login.customer_id needs to point to the people.id field, except id is nested.

```yaml
"""dataset:
  - fides_key: arrays_inside_objects_example
    name: Array inside nested object emaple
    description: Example of a Mongo dataset that contains nested data
    collections:
      - name: people
        fields:
          - name: clients
            fields:
              - name: emails
                data_categories: [user.provided.identifiable]
                fidesops_meta:
                    identity: email
                    data_type: string[]
              - name: id
                data_categories: [system.operations]
                fidesops_meta:
                  primary_key: True
      - name: login
        fields:
          - name: customer_id
            data_categories: [user.derived.identifiable.unique_id]
            fidesops_meta:
              data_type: integer
              references:
                - dataset: arrays_inside_objects_example
                  field: people.clients.id  # collection_name.field_name.dictionary_key
                  direction: from
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              data_type: integer
              primary_key: True
          - name: time
            data_categories: [user.derived.nonidentifiable.sensor]
          
```

**Comment by seanpreston** [comment]
In your dataset

```
"""dataset:
  - fides_key: arrays_inside_objects_example
    name: Array inside nested object emaple
    description: Example of a Mongo dataset that contains nested data
    collections:
      - name: people
        fields:
          - name: clients
            fields:
              - name: emails
                data_categories: [user.provided.identifiable]
                fidesops_meta:
                    identity: email
                    data_type: string[]
              - name: id
                data_categories: [system.operations]
                fidesops_meta:
                  primary_key: True
      - name: login
        fields:
          - name: customer_id
            data_categories: [user.derived.identifiable.unique_id]
            fidesops_meta:
              data_type: integer
              references:
                - dataset: arrays_inside_objects_example
                  field: people.clients.id  # collection_name.field_name.dictionary_key
                  direction: from
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              data_type: integer
              primary_key: True
          - name: time
            data_categories: [user.derived.nonidentifiable.sensor]
```

do you mean for `clients` to look like this:

```
          - name: clients
            fields:
                ...
            fidesops_meta:
                data_type: object[]
```
