### ISSUE TITLE
[Array + JSON Handling] Make Element Matching Configurable for Arrays

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fidesops#193]
### Is your feature request related to a specific problem?

This is being split off of https://github.com/ethyca/fidesops/issues/146, as that PR is getting large.  This also might be worth postponing addressing until we do erasures on arrays.

In array use case discussions, it was brought up that the user might want to configure some array behavior.  Specifically, introducing array support adds some ambiguity into how queries should be built.  A query on an array field (+ field is a `reference` field or contains identity data) may match multiple indices in an array, or multiple subdocuments inside the array.   The default behavior I've built into #146  is that only matched array indices are returned on a document, and only those matched values are used to make subsequent queries.   This is a more conservative approach, in that it selects less/masks less, but may not cover all user's data structures.

(This is separate from the after-the-fact filtering we do on data categories.  This is related to what pieces of array data we return and/or use for other queries).

### Describe the solution you'd like

Allow the user to configure in the dataset yaml that all values in the discovered array field should be returned and/or used to make subsequent queries, if they don't want the default.  Specifically there's a `filter_element_match` method that we run (we do this in code, not at the database level) that removes non matched elements from arrays, but we could be more targeted as to which fields we run this on.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by pattisdr** [comment]
For example, say for the "people" collection we run a query that says "return records where users.id = 1".   
![untitled (1)](https://user-images.githubusercontent.com/9755598/153283374-2b71533d-d20e-4a06-ae27-3f45a7cba58f.png)
That query returns the first record, {"users": ["id": 1, "ccn": 12345, "name": "Dawn"}, {"id": 2, "ccn": 54321", "name": "Jane"}], "employees": []} because it contains the id:1  somewhere in there.   Say we're supposed to use the ccn here to lookup records in the credit card collection.  Because this is an array, filter out the non-matched elements: `{"users": ["id": 1, "ccn": 12345, "name": "Dawn"}], "employees": []} `, save that as the result for the people collection, and then pass this data to the credit card collection to only search for credit cards where the id is 12345.

**Comment by iamkelllly** [comment]
> Specifically there's a `filter_element_match` method that we run (we do this in code, not at the database level) that removes non matched elements from arrays, but we could be more targeted as to which fields we run this on.

I think it makes a lot of sense to have a config per field element to determine whether the adopter wants to filter out any non-applicable array elements for the next query vs keep them for using to query. 

Would the config be something like this? 
`use_entire_array_to_query=true` to use the full array to query the next location
`use_entire_array_to_query=false` to remove non-matched elements in the array when querying the next location
(obviously we need to select a different attribute name)

```yaml
dataset:
  - fides_key: mongo_test
    name: Mongo Example Test Dataset
    description: Example of a Mongo dataset that contains 'details' about customers defined in the 'postgres_example_test_dataset'
    collections:
      - name: people_collection
        fields:
          - name: _id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: ccn
            data_categories: [user.provided.financial.accountnumber]
            fidesops_meta:
              data_type: string[]
              use_entire_array_to_query: true
              references:
                - dataset: mongo_test
                  field: credit_card_collection.id
                  direction: from
          - name: name
            data_categories: [user.provided.identifiable.name]
            fidesops_meta:
              data_type: string
      - name: credit_card_collection
        fields:
          - name: _id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: zip
          - name: balance
...

```
(forgive the broken/bad yaml)
