### ISSUE TITLE
API Key authentication strategy

### ISSUE THREAD

**Issue by galvana** [ethyca/fidesops#334]
### Is your feature request related to a specific problem?

Some API endpoints require an API key to be included in the HTTP request, either in the header or as a query param. A reusable API key auth strategy will allow us to include this api key in each request without having to specify it per endpoint.

### Describe the solution you'd like

A new authentication strategy which will allow the user to include an API key in the header or query params.

**Header**
```
authentication:
  strategy: api_key
  configuration:
    headers:
    - name: Token
      value: <api_token>
 ```

**Query Pararm**
```
authentication:
  strategy: api_key
  configuration:
    query_params:
    - name: token
      value: <api_token>
```

The value in the placeholder `<api_token>` should reference the name of a param in `connector_params` (implied, it won't need to be added as a param value).

### Additional context

This strategy uses a different format to specify required values compared to `basic_authentication` and `bearer_authentication` but this is done to be more inline with the established pattern for params and param values in the `request` field within the SaaS config. The goal will be to use this new format for the other two auth strategies and across the rest of the SaaS config.

Bearer authentication can also be implemented using this new API key strategy since we could just do something like this
```
authentication:
  strategy: api_key
  configuration:
    header:
    - name: Bearer
      value: <api_token>
```
But I believe it is important to have basic and bearer auth as separately named strategies since those are the most commonly used and it might not be clear by the name of the strategy that "api_key" would be a way to implement bearer auth. This new strategy is meant to support non-standard authentication methods that might require the key to be prefixed with custom values or to be placed in a specific location.

Aha! Link: https://ethyca.aha.io/features/OPS-92
